version: '2'

services:
  api:
    build: ./api
    container_name: api
    command: ./docker-start.sh
    ports:
      - '3000:3000'
    volumes:
      - ./api/:/home/app/src/
  web:
    build: ./web
    container_name: web
    command: ./docker-start.sh
    ports:
      - '3001:3001'
    links:
      - api
    volumes:
      - ./web/:/home/app/src/



